# Introduction to Python

<a target="_blank" href="https://colab.research.google.com/github/intro-stat-learning/ISLP_labs/blob/v2.2/Ch02-statlearn-lab.ipynb">
<img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/intro-stat-learning/ISLP_labs/v2.2?labpath=Ch02-statlearn-lab.ipynb)





## Getting Started

To run the labs in this book, you will need two things:

* An installation of `Python3`, which is the specific version of `Python`  used in the labs.
* Access to  `Jupyter`, a very popular `Python` interface that runs code through a file called a *notebook*.

You can download and install  `Python3`   by following the instructions available at [anaconda.com](http://anaconda.com).

 There are a number of ways to get access to `Jupyter`. Here are just a few:

 * Using Google's `Colaboratory` service: [colab.research.google.com/](https://colab.research.google.com/).
 * Using `JupyterHub`, available at [jupyter.org/hub](https://jupyter.org/hub).
 * Using your own `jupyter` installation. Installation instructions are available at [jupyter.org/install](https://jupyter.org/install).

Please see the `Python` resources page on the book website [statlearning.com](https://www.statlearning.com) for up-to-date information about getting `Python` and `Jupyter` working on your computer.

You will need to install the `ISLP` package, which provides access to the datasets and custom-built functions that we provide.
Inside a macOS or Linux terminal type `pip install ISLP`; this also installs most other packages needed in the labs. The `Python` resources page has a link to the `ISLP` documentation website.

To run this lab, download the file `Ch2-statlearn-lab.ipynb` from the `Python` resources page.
Now run the following code at the command line: `jupyter lab Ch2-statlearn-lab.ipynb`.

If you're using Windows, you can use the `start menu` to access `anaconda`, and follow the links. For example, to install `ISLP` and run this lab, you can run the same code above in an `anaconda` shell.


## Basic Commands


In this lab, we will introduce some simple `Python` commands.
 For more resources about `Python` in general, readers may want to consult the tutorial at [docs.python.org/3/tutorial/](https://docs.python.org/3/tutorial/).





Like most programming languages, `Python` uses *functions*
to perform operations.   To run a
function called `fun`, we type
`fun(input1,input2)`, where the inputs (or *arguments*)
`input1` and `input2` tell
`Python` how to run the function.  A function can have any number of
inputs. For example, the
`print()`  function outputs a text representation of all of its arguments to the console.

In [1]:
print('fit a model with', 11, 'variables')


fit a model with 11 variables


 The following command will provide information about the `print()` function.

In [2]:
print?


Adding two integers in `Python` is pretty intuitive.

In [3]:
3 + 5


8

In `Python`, textual data is handled using
*strings*. For instance, `"hello"` and
`'hello'`
are strings.
We can concatenate them using the addition `+` symbol.

In [4]:
"hello" + " " + "world"


'hello world'

 A string is actually a type of *sequence*: this is a generic term for an ordered list.
 The three most important types of sequences are lists, tuples, and strings.  
We introduce lists now.

The following command instructs `Python` to join together
the numbers 3, 4, and 5, and to save them as a
*list* named `x`. When we
type `x`, it gives us back the list.

In [5]:
x = [3, 4, 5]
x


[3, 4, 5]

Note that we used the brackets
`[]` to construct this list.

We will often want to add two sets of numbers together. It is reasonable to try the following code,
though it will not produce the desired results.

In [6]:
y = [4, 9, 7]
x + y


[3, 4, 5, 4, 9, 7]

In [7]:
z = ['Machine learning']
w = [1]
z + w

['Machine learning', 1]

The result may appear slightly counterintuitive: why did `Python` not add the entries of the lists
element-by-element?
 In `Python`, lists hold *arbitrary* objects, and  are added using  *concatenation*.
 In fact, concatenation is the behavior that we saw earlier when we entered `"hello" + " " + "world"`.


This example reflects the fact that
 `Python` is a general-purpose programming language. Much of `Python`'s  data-specific
functionality comes from other packages, notably `numpy`
and `pandas`.
In the next section, we will introduce the  `numpy` package.
See [docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html) for more information about `numpy`.


## Introduction to Numerical Python

As mentioned earlier, this book makes use of functionality   that is contained in the `numpy`
 *library*, or *package*. A package is a collection of modules that are not necessarily included in
 the base `Python` distribution. The name `numpy` is an abbreviation for *numerical Python*.

  To access `numpy`, we must first `import` it.

In [8]:
import numpy as np

In the previous line, we named the `numpy` *module* `np`; an abbreviation for easier referencing.

In `numpy`, an *array* is  a generic term for a multidimensional
set of numbers.
We use the `np.array()` function to define   `x` and `y`, which are one-dimensional arrays, i.e. vectors.

In [9]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

Note that if you forgot to run the `import numpy as np` command earlier, then
you will encounter an error in calling the `np.array()` function in the previous line.
 The syntax `np.array()` indicates that the function being called
is part of the `numpy` package, which we have abbreviated as `np`.

Since `x` and `y` have been defined using `np.array()`, we get a sensible result when we add them together. Compare this to our results in the previous section,
 when we tried to add two lists without using `numpy`.

In [10]:
x + y

array([ 7, 13, 12])

In `numpy`, matrices are typically represented as two-dimensional arrays, and vectors as one-dimensional arrays. {While it is also possible to create matrices using  `np.matrix()`, we will use `np.array()` throughout the labs in this book.}
We can create a two-dimensional array as follows.

In [11]:
x = np.array([[1, 2], [3, 4]])
x


array([[1, 2],
       [3, 4]])

The object `x` has several
*attributes*, or associated objects. To access an attribute of `x`, we type `x.attribute`, where we replace `attribute`
with the name of the attribute.
For instance, we can access the `ndim` attribute of  `x` as follows.

In [12]:
x.ndim

2

The output indicates that `x` is a two-dimensional array.  
Similarly, `x.dtype` is the *data type* attribute of the object `x`. This indicates that `x` is
comprised of 64-bit integers:

In [13]:
x.dtype

dtype('int64')

Why is `x` comprised of integers? This is because we created `x` by passing in exclusively integers to the `np.array()` function.
  If
we had passed in any decimals, then we would have obtained an array of
*floating point numbers* (i.e. real-valued numbers).

In [14]:
np.array([[1, 2], [3.0, 4]]).dtype


dtype('float64')

Typing `fun?` will cause `Python` to display
documentation associated with the function `fun`, if it exists.
We can try this for `np.array()`.

In [15]:
fun?

Object `fun` not found.


In [16]:
import numpy as np

In [17]:
np.array?


This documentation indicates that we could create a floating point array by passing a `dtype` argument into `np.array()`.

In [18]:
np.array([[1, 2], [3, 4]], float).dtype


dtype('float64')

The array `x` is two-dimensional. We can find out the number of rows and columns by looking
at its `shape` attribute.

In [19]:
x.shape


(2, 2)

A *method* is a function that is associated with an
object.
For instance, given an array `x`, the expression
`x.sum()` sums all of its elements, using the `sum()`
method for arrays.
The call `x.sum()` automatically provides `x` as the
first argument to its `sum()` method.

In [20]:
x = np.array([1, 2, 3, 4])
x.sum()

np.int64(10)

We could also sum the elements of `x` by passing in `x` as an argument to the `np.sum()` function.

In [21]:
x = np.array([1, 2, 3, 4])
np.sum(x)

np.int64(10)

 As another example, the
`reshape()` method returns a new array with the same elements as
`x`, but a different shape.
 We do this by passing in a `tuple` in our call to
 `reshape()`, in this case `(2, 3)`.  This tuple specifies that we would like to create a two-dimensional array with
$2$ rows and $3$ columns. {Like lists, tuples represent a sequence of objects. Why do we need more than one way to create a sequence? There are a few differences between tuples and lists, but perhaps the most important is that elements of a tuple cannot be modified, whereas elements of a list can be.}

In what follows, the
`\n` character creates a *new line*.

In [22]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)


beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [23]:
x_reshape.ndim

2

The previous output reveals that `numpy` arrays are specified as a sequence
of *rows*. This is  called *row-major ordering*, as opposed to *column-major ordering*.

`Python` (and hence `numpy`) uses 0-based
indexing. This means that to access the top left element of `x_reshape`,
we type in `x_reshape[0,0]`.

In [24]:
x_reshape[0, 0]

np.int64(1)

Similarly, `x_reshape[1,2]` yields the element in the second row and the third column
of `x_reshape`.

In [25]:
x_reshape[1, 2]

np.int64(6)

In [26]:

x_reshape.shape

(2, 3)

In [27]:
x.shape

(6,)

In [28]:
 x.shape #x has one dimension

(6,)

Similarly, `x[2]` yields the
third entry of `x`.

Now, let's modify the top left element of `x_reshape`.  To our surprise, we discover that the first element of `x` has been modified as well!



In [29]:
# how Python use references than values

In [30]:
print('x before we modify x_reshape:\n', x)


x before we modify x_reshape:
 [1 2 3 4 5 6]


In [31]:
print('x_reshape before we modify x_reshape:\n', x_reshape)


x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]


In [32]:
x_reshape[0, 0] = 5 #for Python, first index is 0
print('x_reshape after we modify its top left element:\n', x_reshape)


x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]


In [33]:
print('x after we modify top left element of x_reshape:\n', x)


x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


Modifying `x_reshape` also modified `x` because the two objects occupy the same space in memory.


    

We just saw that we can modify an element of an array. Can we also modify a tuple? It turns out that we cannot --- and trying to do so introduces
an *exception*, or error.

In [34]:
my_list = [3, 4, 5]
my_list[0] = 2
print(my_list)

[2, 4, 5]


We now briefly mention some attributes of arrays that will come in handy. An array's `shape` attribute contains its dimension; this is always a tuple.
The  `ndim` attribute yields the number of dimensions, and `T` provides its transpose.

In [35]:
x_reshape.shape


(2, 3)

In [36]:
x_reshape.ndim

2

In [37]:
x_reshape.T

array([[5, 4],
       [2, 5],
       [3, 6]])

Notice that the three individual outputs `(2,3)`, `2`, and `array([[5, 4],[2, 5], [3,6]])` are themselves output as a tuple.

We will often want to apply functions to arrays.
For instance, we can compute the
square root of the entries using the `np.sqrt()` function:

In [38]:
np.sqrt(x)


array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

We can also square the elements:

In [39]:
x**2


array([25,  4,  9, 16, 25, 36])

We can compute the square roots using the same notation, raising to the power of $1/2$ instead of 2.

In [40]:
x**0.5


array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

Throughout this book, we will often want to generate random data.
The `np.random.normal()`  function generates a vector of random
normal variables. We can learn more about this function by looking at the help page, via a call to `np.random.normal?`.
The first line of the help page  reads `normal(loc=0.0, scale=1.0, size=None)`.
 This  *signature* line tells us that the function's arguments are  `loc`, `scale`, and `size`. These are *keyword* arguments, which means that when they are passed into
 the function, they can be referred to by name (in any order). {`Python` also uses *positional* arguments. Positional arguments do not need to use a keyword. To see an example, type in `np.sum?`. We see that `a` is a positional argument, i.e. this function assumes that the first unnamed argument that it receives is the array to be summed. By contrast, `axis` and `dtype` are keyword arguments: the position in which these arguments are entered into `np.sum()` does not matter.}
 By default, this function will generate random normal variable(s) with mean (`loc`) $0$ and standard deviation (`scale`) $1$; furthermore,
 a single random variable will be generated unless the argument to `size` is changed.

We now generate 50 independent random variables from a $N(0,1)$ distribution.

In [41]:
np.random.normal?

In [42]:
x = np.random.normal(size=50)
x


array([-0.0948445 ,  1.04149445, -0.53476661,  0.10468252, -0.17187382,
        0.60755995,  1.05122351, -0.84084567, -1.27263638, -0.60047221,
        1.63452714,  0.93182174,  0.21136738, -0.31064394, -0.35528194,
       -0.96263503,  0.55000992,  0.74455622, -0.5139309 ,  1.90256236,
       -0.25510225,  0.23224595, -1.32363608,  1.1516968 ,  1.30525284,
       -0.96770133, -0.85116155,  0.25832025, -0.83393318, -2.49219288,
       -0.4102617 ,  0.46604289, -0.0277474 , -0.54877365, -0.48515483,
       -1.56831245,  0.04486164, -0.47674675, -0.95679083,  1.05432743,
       -0.04682962, -0.45419395,  0.9576329 , -0.42154131,  0.29472812,
       -1.93076147,  1.35056348, -0.73007902, -0.93722874, -1.20307088])

We create an array `y` by adding an independent $N(50,1)$ random variable to each element of `x`.

In [43]:
y = x + np.random.normal(loc=50, scale=1, size=x.shape[0])

The `np.corrcoef()` function computes the correlation matrix between `x` and `y`. The off-diagonal elements give the
correlation between `x` and `y`.

In [44]:
np.corrcoef(x, y)

array([[1.        , 0.65728968],
       [0.65728968, 1.        ]])

If you're following along in your own `Jupyter` notebook, then you probably noticed that you got a different set of results when you ran the past few
commands. In particular,
 each
time we call `np.random.normal()`, we will get a different answer, as shown in the following example.

In [45]:
print(np.random.normal(scale=5, size=2))
print(np.random.normal(scale=5, size=2))


[-0.45143059  3.390579  ]
[-8.44441434 -7.44204259]


In order to ensure that our code provides exactly the same results
each time it is run, we can set a *random seed*
using the
`np.random.default_rng()` function.
This function takes an arbitrary, user-specified integer argument. If we set a random seed before
generating random data, then re-running our code will yield the same results. The
object `rng` has essentially all the random number generating methods found in `np.random`. Hence, to
generate normal data we use `rng.normal()`.

In [46]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


Throughout the labs in this book, we use `np.random.default_rng()`  whenever we
perform calculations involving random quantities within `numpy`.  In principle, this
should enable the reader to exactly reproduce the stated results. However, as new versions of `numpy` become available, it is possible
that some small discrepancies may occur between the output
in the labs and the output
from `numpy`.

The `np.mean()`,  `np.var()`, and `np.std()`  functions can be used
to compute the mean, variance, and standard deviation of arrays.  These functions are also
available as methods on the arrays.

In [47]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)


In [48]:
y

array([ 2.04091912, -2.55566503,  0.41809885, -0.56776961, -0.45264929,
       -0.21559716, -2.01998613, -0.23193238, -0.86521308,  3.32299952])

In [49]:
np.mean(y), y.mean()

(np.float64(-0.1126795190952861), np.float64(-0.1126795190952861))

In [50]:
np.var(y), y.var()

(np.float64(2.7243406406465125), np.float64(2.7243406406465125))

In [51]:
((y - y.mean())**2).mean()

np.float64(2.7243406406465125)

In [52]:
np.mean((y - y.mean())**2)

np.float64(2.7243406406465125)

In [53]:
import numpy as np

rng = np.random.default_rng(3)
y_1 = rng.standard_normal(1_000_000)
y_1.mean()


np.float64(0.000566671881845236)

Notice that by default `np.var()` divides by the sample size $n$ rather
than $n-1$; see the `ddof` argument in `np.var?`.


In [54]:
np.var?

In [55]:
np.sqrt(np.var(y)), np.std(y)

(np.float64(1.6505576756498128), np.float64(1.6505576756498128))

The `np.mean()`,  `np.var()`, and `np.std()` functions can also be applied to the rows and columns of a matrix.
To see this, we construct a $10 \times 3$ matrix of $N(0,1)$ random variables, and consider computing its row sums.

In [56]:
X = rng.standard_normal((10, 3))
X

array([[ 0.06390987, -0.69728734,  1.10667393],
       [ 1.13669379, -0.98405408, -1.8553297 ],
       [-0.45448713, -1.76981523,  0.16652804],
       [ 0.14186459,  0.01527474,  0.67105504],
       [-0.62748466, -0.77820197, -1.69791225],
       [ 0.06323824, -0.04128639,  0.67514514],
       [-0.77875359,  0.86144194,  0.24113401],
       [-0.78309185,  2.02323159,  0.48078093],
       [-0.84158817,  0.14350929,  0.99826914],
       [-1.73886096, -0.29012588, -2.18026303]])

Since arrays are row-major ordered, the first axis, i.e. `axis=0`, refers to its rows. We pass this argument into the `mean()` method for the object `X`.

In [57]:
rng.standard_normal?

In [58]:
X.mean(axis=0)

array([-0.38185599, -0.15173133, -0.13939188])

The following yields the same result.

In [59]:
X.mean(0)

array([-0.38185599, -0.15173133, -0.13939188])

## Sequences and Slice Notation

As seen above, the
function `np.linspace()`  can be used to create a sequence
of numbers.

In [60]:
np.linspace?

In [61]:
seq1 = np.linspace(0, 10, 11)
seq1


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

The function `np.arange()`
 returns a sequence of numbers spaced out by `step`. If `step` is not specified, then a default value of $1$ is used. Let's create a sequence
 that starts at $0$ and ends at $10$.

In [62]:
seq2 = np.arange(0, 10)
seq2


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Why isn't $10$ output above? This has to do with *slice* notation in `Python`.
Slice notation  
is used to index sequences such as lists, tuples and arrays.
Suppose we want to retrieve the fourth through sixth (inclusive) entries
of a string. We obtain a slice of the string using the indexing  notation  `[3:6]`.

In [63]:
"hello world"[3:6]

'lo '

In the code block above, the notation `3:6` is shorthand for  `slice(3,6)` when used inside
`[]`.

In [64]:
"hello world"[slice(3,6)]


'lo '

You might have expected  `slice(3,6)` to output the fourth through seventh characters in the text string (recalling that  `Python` begins its indexing at zero),  but instead it output  the fourth through sixth.
 This also explains why the earlier `np.arange(0, 10)` command output only the integers from $0$ to $9$.
See the documentation `slice?` for useful options in creating slices.

    



    


    



    



    


    


## Indexing Data
To begin, we  create a two-dimensional `numpy` array.

In [65]:
A = np.array(np.arange(16)).reshape((4, 4))
A



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Typing `A[1,2]` retrieves the element corresponding to the second row and third
column. (As usual, `Python` indexes from $0.$)

In [66]:
A[1,2]


np.int64(6)

The first number after the open-bracket symbol `[`
 refers to the row, and the second number refers to the column.

### Indexing Rows, Columns, and Submatrices
 To select multiple rows at a time, we can pass in a list
  specifying our selection. For instance, `[1,3]` will retrieve the second and fourth rows:

In [67]:
A[[1,3]] #list inside bracket --> select multiple row


array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

To select the first and third columns, we pass in  `[0,2]` as the second argument in the square brackets.
In this case we need to supply the first argument `:`
which selects all rows.

In [68]:
A[:,[0,2]]


array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

Now, suppose that we want to select the submatrix made up of the second and fourth
rows as well as the first and third columns. This is where
indexing gets slightly tricky. It is natural to try  to use lists to retrieve the rows and columns:

In [69]:
A[[1,3],[0,2]]


array([ 4, 14])

 Oops --- what happened? We got a one-dimensional array of length two identical to

In [70]:
np.array([A[1,0],A[3,2]])


array([ 4, 14])

 Similarly,  the following code fails to extract the submatrix comprised of the second and fourth rows and the first, third, and fourth columns:

In [86]:
[A[1,0],A[3,2]]

[np.int64(4), np.int64(14)]

In [87]:
# A[[1,3],[0,2,3]] -> errors
#shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,)



We can see what has gone wrong here. When supplied with two indexing lists, the `numpy` interpretation is that these provide pairs of $i,j$ indices for a series of entries. That is why the pair of lists must have the same length. However, that was not our intent, since we are looking for a submatrix.

One easy way to do this is as follows. We first create a submatrix by subsetting the rows of `A`, and then on the fly we make a further submatrix by subsetting its columns.


In [72]:
A[[1,3]][:,[0,2]] #does it in two steps: first pick rows, then pick columns → full 2×2 block.


array([[ 4,  6],
       [12, 14]])

There are more efficient ways of achieving the same result.

The *convenience function* `np.ix_()` allows us  to extract a submatrix
using lists, by creating an intermediate *mesh* object.

In [73]:
idx = np.ix_([1,3],[0,2,3])
A[idx]


array([[ 4,  6,  7],
       [12, 14, 15]])

Alternatively, we can subset matrices efficiently using slices.
  
The slice
`1:4:2` captures the second and fourth items of a sequence, while the slice `0:3:2` captures
the first and third items (the third element in a slice sequence is the step size).

In [74]:
A[1:4:2,0:3:2] #start:stop:step works just like Python list slicing.


array([[ 4,  6],
       [12, 14]])

Why are we able to retrieve a submatrix directly using slices but not using lists?
Its because they are different `Python` types, and
are treated differently by `numpy`.
Slices can be used to extract objects from arbitrary sequences, such as strings, lists, and tuples, while the use of lists for indexing is more limited.




    



    



### Boolean Indexing
In `numpy`, a *Boolean* is a type  that equals either   `True` or  `False` (also represented as $1$ and $0$, respectively).
The next line creates a vector of $0$'s, represented as Booleans, of length equal to the first dimension of `A`.

In [75]:
A.shape[0]

4

In [76]:
np.zeros(A.shape[0])

array([0., 0., 0., 0.])

In [77]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

array([False, False, False, False])

We now set two of the elements to `True`.

In [78]:
keep_rows[[1,3]] = True
keep_rows


array([False,  True, False,  True])

Note that the elements of `keep_rows`, when viewed as integers, are the same as the
values of `np.array([0,1,0,1])`. Below, we use  `==` to verify their equality. When
applied to two arrays, the `==`   operation is applied elementwise.

In [79]:
np.all(keep_rows == np.array([0,1,0,1]))


np.True_

(Here, the function `np.all()` has checked whether
all entries of an array are `True`. A similar function, `np.any()`, can be used to check whether any entries of an array are `True`.)

   However, even though `np.array([0,1,0,1])`  and `keep_rows` are equal according to `==`, they index different sets of rows!
The former retrieves the first, second, first, and second rows of `A`.

In [80]:
A[np.array([0,1,0,1])] #This means: “Give me rows 0, 1, 0, 1, in that order.”


array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

 By contrast, `keep_rows` retrieves only the second and fourth rows  of `A` --- i.e. the rows for which the Boolean equals `TRUE`.

In [81]:
A[keep_rows]


array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

This example shows that Booleans and integers are treated differently by `numpy`.

We again make use of the `np.ix_()` function
 to create a mesh containing the second and fourth rows, and the first,  third, and fourth columns. This time, we apply the function to Booleans,
 rather than lists.

In [82]:
keep_cols = np.zeros(A.shape[1], bool)
keep_cols[[0, 2, 3]] = True
idx_bool = np.ix_(keep_rows, keep_cols)
A[idx_bool]


array([[ 4,  6,  7],
       [12, 14, 15]])

We can also mix a list with an array of Booleans in the arguments to `np.ix_()`:

In [83]:
idx_mixed = np.ix_([1,3], keep_cols)
A[idx_mixed]


array([[ 4,  6,  7],
       [12, 14, 15]])

For more details on indexing in `numpy`, readers are referred
to the `numpy` tutorial mentioned earlier.


To exit `Jupyter`,  select `File / Shut Down`.



